name = "cardanofoundation/cardano-ibc"
version = "0.2.0"
compiler = "v1.1.21"
plutus = "v3"
description = "The project involves implementing the Inter-Blockchain Communication (IBC) protocol on the Cardano main chain using Aiken."

[repository]
user = "aiken-lang"
project = "cardano-ibc"
platform = "gitlab"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2.2.0"
source = "github"

[config]
