app-db-backend = ''
halt-height = 0
halt-time = 0
iavl-cache-size = 781250
iavl-disable-fastnode = false
iavl-fastnode-module-whitelist = ['lockup']
iavl-lazy-loading = false
index-events = []
inter-block-cache = true
min-retain-blocks = 0
minimum-gas-prices = '0uosmo'
pruning = 'default'
pruning-interval = '0'
pruning-keep-recent = '0'

[api]
address = 'tcp://0.0.0.0:1317'
enable = true
enabled-unsafe-cors = true
max-open-connections = 1000
rpc-max-body-bytes = 1000000
rpc-read-timeout = 10
rpc-write-timeout = 0
swagger = true

[grpc]
address = '0.0.0.0:9090'
enable = true
log-queries = false
max-recv-msg-size = '10485760'
max-send-msg-size = '2147483647'

[grpc-web]
address = '0.0.0.0:9091'
enable = true
enable-unsafe-cors = true

[mempool]
max-txs = '5000'

[osmosis-mempool]
adaptive-fee-enabled = "true"
arbitrage-min-gas-fee = "0.1"
max-gas-wanted-per-tx = "60000000"
min-gas-price-for-high-gas-tx = "0.0025"

[osmosis-sqs]
db-host = 'redis'
grpc-ingest-address = '0.0.0.0:50051'
grpc-ingest-max-call-size-bytes = '52428800'
is-enabled = 'true'
route-cache-enabled = 'true'

[rosetta]
address = ':8080'
blockchain = 'app'
denom-to-suggest = 'uatom'
enable = false
enable-fee-suggestion = false
gas-to-suggest = 200000
network = 'network'
offline = false
retries = 3

[state-sync]
snapshot-interval = 0
snapshot-keep-recent = 2

[store]
streamers = []

[streamers]
[streamers.file]
fsync = 'false'
keys = ['*']
output-metadata = 'true'
prefix = ''
stop-node-on-error = 'true'
write_dir = ''

[telemetry]
enable-hostname = false
enable-hostname-label = false
enable-service-label = false
enabled = false
global-labels = []
prometheus-retention-time = 0
service-name = ''

[wasm]
memory_cache_size = 1000
query_gas_limit = 3000000
