version: '3.9'
services:
  relayer-service:
    container_name: relayer
    build:
      context: ../
      dockerfile: ./relayer/Dockerfile
    volumes:
      - ~/.relayer:/root/.relayer
    network_mode: "host"
    env_file:
      - ./.env
